"""initial_schema

Revision ID: 56455943753d
Revises: 
Create Date: 2026-06-20 15:52:18.892506

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '56455943753d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
